### ISSUE TITLE
Create an alternative to CTS via local (R)OpenBabel

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#109]
Work towards making CTS optional, by calling obabel locally. 
Add "queryCTS=TRUE" to mbWorkflow, and do local calls otherwise.
Also edit the CTS timeout error message to hint that "queryCTS=FALSE" might help.

**Comment by schymane** [comment]
Mandatory fields from the MassBank point of view:
CH$NAME
CH$SMILES <= assuming this is our starting point
CH$IUPAC <= the InChI (not InChI Key)
Other mandatory compound fields CH$FORMULA, CH$EXACT_MASS and CH$COMPOUND_CLASS should be filled in from somewhere else in RMB, not CTS.

All other compound fields are optional from the MassBank point of view, but still useful for us.
CH$LINK: CAS <= you can default this to take it from the compound list (the optional column) if available, or leave empty if not.
CH$LINK: INCHIKEY <= we need to get the InChI Key to get the remaining identifiers and do the cross-checks
CH$LINK: PUBCHEM CID:
CH$LINK: CHEMSPIDER

PubChem: 
https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST.html
ChemSpider: 
http://www.chemspider.com/Search.asmx
e.g.
http://www.chemspider.com/Search.asmx?op=SimpleSearch
would work on both SMILES or Name from the database or, for more exact results, the InChI Key.
They also have 
http://www.chemspider.com/InChI.asmx
You should also be able to retrieve names once we have the CSID, Christoph should be able to help you there?

I wonder actually if ChemSpider could be a better option? It will take both dbname and smiles (Babel won't work with names) and we will have to get at least one alternative CH$NAME from somewhere - babel also can't do this (unless I am mistaken?).
You will need a token though. And if this is our back-up, we'd need to ask people to enter a token in their settings files, or prompt them for it, or ask ChemSpider if we can have an "RMassBank" token - but, this shouldn't appear in the code, right @sneumann ?

**Comment by ermueller** [comment]
So, I've got this implemented more or less, currently testing if everything works fine with different datasets. Currently no IDs or 

1)
 I'm on the edge about using chemspider or pubchem, since, like I said, it would be nice to do this without any need for a working internet connection. I also currently have a dataset with some names/SMILES-codes without anything in any database, which also crashes RMassBank.
(You can see for yourself, one smiles-code in question is:
````
O=C(OC)c1c(C)nc(COCCN)c(c1c2ccccc2O)C(=O)OCC
````
)

2) 
Actually, IUPAC-Names can be generated without any need for a database (since they're unambiguous), but it's commercial only :/ No open-source package for that. And even the commercial ones are kinda "meh" as far as I read.

Currently, for offline functionality, we have to require a Compound name. Is that ok?

3)
Also, I'm pretty sure the chemspider-token would have to be in the code one way or another, so that's an issue. We would need an external service to actually make the HTTP call to chemspider. 
We could relay the request per IPB/UFZ/EAWAG and then the token would be safe, but that is a hassle because it would just add another server dependancy which is the opposite of what we want.

There are safe-ish measures to do it without relaying, but if somebody really wanted to he could always retrieve the token as long as it is within RMassBank.

**Comment by schymane** [comment]
(1) If the SMILES and/or name isn't in a database, this shouldn't crash RMassBank, it should just result in a quite empty infolist result? We have run RMassBank in the past with transformation products that weren't yet in any database. However, for these cases we did always have a SMILES and a name. If either SMILES or Name missing results in a crash, this should be another issue, because that should be caught so the user can fill in their compound list.

(2) yes, IUPAC names can be generated without a database but I am also not aware of an open option for that. ACD ChemSketch offers this up to 50 atoms without more than 3 rings but e.g. won't do the example you sent. 
Do you mean for offline functionality we have to require both name and SMILES? Without the SMILES we also can't do much....but without any name, we also can't generate valid records.

(3) If we did go for the online-backup option, we could look at contacting ChemSpider to get a "RMassBank" token for the code only (i.e. not our personal one) and we make it as safe as possible, but if it were misused they could just block it and reissue a new one? The fewer server dependencies the better, I agree.

**Comment by tsufz** [comment]
add 1) / 2) SMILES and IUPAC are mandatory for MassBank and thus empty fields will not crash RMassBank, but records cannot be uploaded.

add 2) Yes, there is an open source parser: http://opsin.ch.cam.ac.uk/. Of course one could run locally Chemaxon or ACD suite if available. I would rather argue for a solution that is independent from any commercial software.

add 3) How will you hide the token in open software? It is quite easy to get a token from Chemspider, we need only an option field to deploy the private token.

**Comment by ermueller** [comment]
> (1) If the SMILES and/or name isn't in a database, this shouldn't crash RMassBank, it should just 
> result in a quite empty infolist result? We have run RMassBank in the past with transformation 
> products that weren't yet in any database. However, for these cases we did always have a SMILES 
> and a name. If either SMILES or Name missing results in a crash, this should be another issue, 
> because that should be caught so the user can fill in their compound list.

Ok, I think I said something wrong here:
If the name is overly complex with all kinds of brackets and who knows what (IUPAC-like, I'd say) then CTS just times out because it doesn't quite know what to do.
If CTS can interpret the name but doesn't know anything, then yes, it just returns nothing.

> Do you mean for offline functionality we have to require both name and SMILES? 

Exactly. Nothing we can do about that, as far as I see it.

> (3) If we did go for the online-backup option, we could look at contacting ChemSpider to get a 
> "RMassBank" token for the code only (i.e. not our personal one) and we make it as safe as possible, 
> but if it were misused they could just block it and reissue a new one? The fewer server 
> dependencies the better, I agree.

But if somebody knew how to get the token, then we'd have to implement it in a totally different way, because there'd already be somebody who knew how to get the token. That's the main problem: We can hide it in a rather sophisticated way, but that will do nothing if somebody actually wanted to get the token.
Although - if you practically just have to ask the Chemspider guys nicely for a token, then why even hide it in an absurd way?

@tsufz
2) Opsin just parses from name to other identifiers and not vice versa, as far as I read. Everywhere it turns up it says "name-to-structure-conversion" and not the other way around.

3) We could do something with precompiling Java to bytecode. Then, if somebody wanted to know the token, he'd have to decompile it to get the token. This is the safest method I can think of, but it's also by far the hardest to implement. 
But like I said, if you just have to register with Chemspider then I see no real reason to hide the token in such an absurd way.

**Comment by tsufz** [comment]
@ermueller 
Yes, you are right. I does not work vice-versa. Sorry, I didn't check ti....

**Comment by meowcat** [comment]
(copied from email)
Hi Erik @ermueller,

I and Emma just played around a bit and found that the PubChem REST PUG thing is actually quite cool and might substitute for CTS for many things.
You can access it with URL directly and get the output as different things, here for example JSON which is easy to handle with R.

Look for example at:

http://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/inchikey/MXWJVTOOROXGIU-UHFFFAOYSA-N/synonyms/json
(the first synonyms seems to be good usually)

http://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/inchikey/MXWJVTOOROXGIU-UHFFFAOYSA-N/record/json
(has the IUPAC name, for example. Also, the structure with coordinates if we should ever need it)

http://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/inchikey/MXWJVTOOROXGIU-UHFFFAOYSA-N/description/json
(Title is one way of getting the name)

and there is more in there we can use, check http://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST.html

I just ran a test with 25 SMILES from our list. It failed only on two (Z-Tepraloxydim and E-Tepraloxydim) but this could probably be remediated if you integrate an InChIkey destereochemistryzation (replace the stereochemistry hash IOYNQIMAUDJVEI-KUNSGPAMSA-N by the "flat" IOYNQIMAUDJVEI-UHFFFAOYSA-N) as a fallback.

Check here for my test code: https://gist.github.com/meowcat/9e9e66a5cd0bc90f08e1

What do you think, maybe we can use some of that stuff?

**Comment by meowcat** [comment]
We looked a bit more and it seems that we can't get a ChemSpider ID from PubChem - the only way we found is to get the CSID list from Cactus and use the lowest one. I just updated the gist code to get that (and renamed inputSmiles to inputInChIKey, since I had messed that up :) ) It fails on two entries (flumioxazin and propyzamide) out of my 25, but it's the best we currently know outside of CTS.

**Comment by tsufz** [comment]
I we have the InCHI, we can retrieve the CSID directly from CS without token:
http://www.chemspider.com/InChI.asmx?op=InChIToCSID

same with key:
http://www.chemspider.com/InChI.asmx?op=InChIKeyToCSID

I am curious why they don't ask for token in this case. I could ask them for clarification or if they plan to depreciate. It is a follow up of the recent email communication with Emma (they asked why we use CTS to retrieve CSID).

**Comment by schymane** [comment]
The InChI Services seem new, so I don’t think they will deprecate.
They are on a different page to their other web services, we discovered it just after sending the CACTUS mail.
We already have the code, Michele’s just polishing it up to catch the cases where the key is invalid or the result is empty.
We got 25 of 25 records back :-) and without a token.

**Comment by meowcat** [comment]
Yeah, we just also found the ChemSpider service here and it seems to work great. Updated the gist code again: https://gist.github.com/meowcat/9e9e66a5cd0bc90f08e1

Works for all 25 tested InChI keys.

@ermueller: In an email you had a long IUPAC-style name you couldn't get parsed... however not even ChemDraw can parse that one, I wonder if the name is correct? What would the molecule look like and where did you get the name from? (I admit I'm too lazy to try and draw it myself :) )

**Comment by ermueller** [comment]
Hi

wow, this is a lot of development, and it's pretty cool, too. Let me try to summarize:

1) Use Cactus (or babel) for Inchikey and Inchi
2) Use Pubchem for names and Pubchem CID
3) Use Chemspider for CSID
4) Use CTS for all other external databases (Chebi, CAS, HMDB, Kegg, Lipidmaps)

?

Should the function try to switch things around, in case one of these is down? "Automatic alternative"?

1. Cactus
if down,
-> 1.5. CTS tries to use the name to retrieve the Inchikey and Inchi

2. Pubchem
if down,
-> 4. CTS additionally tries to retrieve Names and Pubchem CID

3. Chemspider
if down,
->  4. CTS additionally tries to retrieve CSID


I'd have to more or less rewrite #101 gatherData, but I'm fine with that.

**Comment by meowcat** [comment]
We think it's a good idea. I would even take CAS from PubChem:
https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/inchikey/WIIZWVCIJKGZOK-RKDXNWHRSA-N/xrefs/RN/json

(and take the smallest, which I think is a good rule of thumb)

Chebi could also be taken from Pubchem synonyms list (the one prefixed with CHEBI: ). I just tested it with the 25 list and it actually works - it returns 12 unique CHEBI entries, one result with 2 CHEBI entries, the 2 tepraloxydims still don't work, and the others apparently don't have a CHEBI associated in PubChem. Notably our original list only had 1 out of 25 CHEBIs retrieved from CTS. 

I opened an additional gist for that one because the other one becomes confusing:
https://gist.github.com/meowcat/857198f57a47aeeef822

**Comment by ermueller** [comment]
Should I always prefer babel over Cactus if there is a babeldir supplied?

@meowcat 
Yeah, I like that idea very much.
I'm just not sure on the priorities if different databases have differing results.

**Comment by schymane** [comment]
>Should I always prefer babel over Cactus if there is a babeldir supplied?
Yes, why not?

>I'm just not sure on the priorities if different databases have differing results.
1st priorities: ChemSpider ID from ChemSpider; PubChemID from PubChem.
Names: we can fill in at least 3 of those, so take three different ones, e.g. PubChem Title, IUPAC Name from one of the sources and e.g. dbname (the user-supplied name). As long as the IUPAC name does not land in first place! We need a short name to also be the "main" name where possible.
The CAS and ChEBI results from PubChem looked better than CTS, so maybe take PubChem as the first source of preference, ChemSpider 1st preference for the ChemSpiderIDs, CTS second preference and CACTUS last, as their results do not appear to be sorted / easily selectable.

Or, if you follow Michele's "rules of thumb" and always take the lowest CAS etc, you could apply that to all retrieved...but I would personally prefer a consistent source if possible, because you get to know predictable issues and this helps the double-checking.

**Comment by meowcat** [comment]
But how to implement the "priority" thing... maybe the results returned by each lookup function could be key -> c(value = x, priority = n) and the finalRecord filling code overwrites the current value with the new value if the priority tag is higher than the currently set one...

**Comment by schymane** [comment]
So, I'm really happy with this :-) One teeny tiny bug that keeps recurring is that during the name check, capitalization seems to slip through, i.e.
Rifaximin, rifaximin
Salicyclic acid, Salicyclic Acid
and so on appear as two of the three names. 
Since these are trivial repeats, I'm deleting them for the moment (first capitalized, where relevant second small is the preference).

In some very rare cases (Rifaximin is one example), the InChI / Systematic name is not coming through, so I only get two trivial names and no long one. Is this missing for one of the less-commonly-used data retrievals?

**Comment by schymane** [comment]
Not that we have an immediate need for it, but this looks neat, if we ever have to deal with systematic names: http://opsin.ch.cam.ac.uk/
