### ISSUE TITLE
CTS mirror server in EU

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#110]
Gert is a big fan of this idea:
- runs using jetty
- backend postreSQL database server v1.9
- database dump ~max 75 GB at this stage.

Biggest issue will be software/data version compatibility between the systems.
Potential servers Halle or Leipzig.

**Comment by tsufz** [comment]
There are some traffic problems (overload due to heavy usage of the Webinterface instead the batch and REST services). Diego considers to implement KNIME nodes and will add some code snippets and documentation to CTS site.

The overall traffic is not to big (~500 visits per month), but enough to knock out the server....

**Comment by tsufz** [comment]
The server requirements are:
- Linux virtual machine
- 4 cores
- 8-16 GB RAM

Backup service not really necessary in order of mirroring the main server in USA?

**Comment by tsufz** [comment]
Needs to be discussed during the workshop next week, right?

**Comment by tsufz** [comment]
Hi, are there any proposals from Olivers side? I guess, there was some time to talk about during your recent workshop?

**Comment by schymane** [comment]
We decided with Gert that there are more pressing issues for the moment, esp. wrt MoNA. So this is on ice
________________________________________

**Comment by meowcat** [comment]
@tsufz @schymane I guess this is not a consideration anymore?

**Comment by tsufz** [comment]
I don't think so.
