### ISSUE TITLE
mzR scan out of bounds error & seqNum

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#127]
Christoph Moschet's Agilent TOF data returned "scan out of bounds" errors using mzR.
The acquisitionNum (which is used in the mzR workflow) was huge for these files, if Erik uses seqNum instead only for the direct retrieval of the peaks, the error goes away and we get records which appear reasonably consistent with the screenshot Christoph sent us. If Erik implements this globally it seems to work for all the cases he tried so far.
@meowcat what is your opinion? would changing the mzR workflow to seqNum instead of aquisitionNum just to get the peaks be the right thing to do? Using aquisitionNum as the identifier later on still works fine.

**Comment by meowcat** [comment]
I am aware that there are these two IDs and I never got to investigate which is which, and which is better to use... (For Orbitrap they are always the same I think.) I believe if *seqNum* works then it is probably the better / right choice. Also if consistency is gained by always using *seqNum* (also as an identifier later) instead of *acquisitionNum* that would probably be a good thing (but not urgent.)

**Comment by schymane** [comment]
I've just rediscovered this error in a new set of Agilent files
w <- msmsRead(w,filetable = fileList, readMethod = "mzR", mode="pH")
|   0%Index whichScan out of bounds [1 ... 2310].

Since we have the fix already - can we add a "switch" in the settings to choose between using seqNum and acquisitionNum, if we aren't sure yet if it's a global fix?

sessionInfo(): RMassBank_1.99.10

**Comment by schymane** [comment]
On second thoughts... a TRUE/FALSE option in msmsRead would be better than changing the settings file...

**Comment by sneumann** [comment]
Quick workaround: `perl -i -pe 's/(<scan num=\")[0-9]*\"(.*)/"$1" . ++$n . "\""/ge'  file.mzXML` 
will renumber the Agilent file inplace to have consecutive `scan num` starting from 1. This will NOT renumber references like "parent scan=XXX" (haven't seen those in the file I had) and only works for mzXML.

**Comment by meowcat** [comment]
The paradigm since some time is that (at least for the MSMS workflow, not sure about MB workflow) settings file entries are (almost?) always also arguments to single functions. See e.g. ?findMsMsHR. So we should do this the same way probably. So it would go as an option to findMsMsHR and as an option in the settings file (but, currently, not as a "eigenständige" option to msmsRead, since it actually gets passed with the "settings" parameter, see ?msmsRead.)

Would there be reasons to make it different?

Another possibility for a quick fix, inside R instead of outside:
* get the header with header(filename)
* manually copy seqNum to acquisitionNum or vice versa,
* and using headerCache with the modified header.

**Comment by uchem-massbank** [comment]
I’m all for consistency – it’d fit well under the fillPrecursorScan setting ;)
The TRUE/FALSE switch was easier for me to build into a findEIC.seqNum() function without recompiling the whole package, but I also didn’t manage to catch all the cases it seems – I got partial results but it still spewed out error messages at me. Steffen seems to have had more success with a brute force fix of the mzXMLs – but now we have too many peaks ;) This is not a good solution in the long run, a setting option would be much better.

**Comment by meowcat** [comment]
The correct solution seems to be that `seqNum` is needed to find the correct scan to extract with `mzR::peaks`, but `acquisitionNum` is needed to find the correct precursor scan. This is also in the code now.
