### ISSUE TITLE
PubChem CID label missing?

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#130]
Latest infolist entries appear to be missing the CID: in front of the PubChem number, which leads to MassBank linking the SID instead of CID. 
When I tried to reproduce this on the RMB_1.9.6 with the demo data I got an empty infolist instead (so something went seriously wrong there) - can someone check if current infolists contain the CID: at the beginning of the PubChem entries or not? If NOT, this needs to be fixed please!

**Comment by ermueller** [comment]
Is fixed in my bioc2014 branch in 6dcb8de .
I'll clean up my branches some time later, since it isn't 2014 anymore... I'm just really really scared I'd break something in git.

**Comment by ermueller** [comment]
Wait:
https://github.com/MassBank/RMassBank/issues/117
Now I'm kind of confused.

**Comment by uchem-massbank** [comment]
Hmm, so am I. I can’t recall how #117 came about but we need the “CID: “ at the front of all PubChem IDs otherwise MassBank does an automatic link to the SID instead of the CID and the identifier links are all completely wrong.
e.g. from an old infolist entry, where we have the CID:
http://massbank.ufz.de/MassBank/jsp/Dispatcher.jsp?type=disp&id=EQ290003&site=1
whereas here is one of the new ones:
http://massbank.ufz.de/MassBank/jsp/Dispatcher.jsp?type=disp&id=EQ338309&site=1
Which is linked to the SID:
CH$LINK: PUBCHEM 9340<http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?sid=9340>
https://pubchem.ncbi.nlm.nih.gov/substance/9340
and not the (correct) CID:
https://pubchem.ncbi.nlm.nih.gov/compound/9340

I guess the problem with #117 was that it was inconsistent and we made the wrong call to remove the CID instead of adding it where it was missing … but I now basically have to reupload several thousand records because they are all linked to the SID :-(

**Comment by meowcat** [comment]
Seems to be done now
