### ISSUE TITLE
Duplicate isotope-annotated peaks

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#132]
Erik has a more extensive email with the details, this issue is just for the record.
e.g.:AU117802:
  295.1533 C15[13]CH18N6+ 1 295.1626 -31.74
  295.1533 C15[13]CH18N6+ 1 295.1626 -31.74

**Comment by ermueller** [comment]
I found the error, but this led to me finding some other small inconsistencies in the checkIsotopes function. For example, some isotope peaks have altogether different formulas than the monoisotopic ones. Still trying to find out why.

However, this also brings good news with it, since me breaking up the function gave me some ideas on how to make the annotation more consistent altogether. :)

**Comment by ermueller** [comment]
Fixed it in 8f7a0ef4c01b9cff06db5714029e8849b5d82877

The isotope annotatin is also slowly but steadily getting better with every small idea :)
