### ISSUE TITLE
Error in msmsWorkflow Step 2

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#154]
msmsWorkflow: Step 2. First analysis pre recalibration
|   0%Error in `[.data.frame`(childPeaks, , colnames(childPeaksOmitted), drop = FALSE) : 
  undefined columns selected

Reproducible with whole dataset or the first subset, all other datasets today have worked fine.
@ermueller @meowcat will have separate email with w and workspace. Good ideas welcome.

> sessionInfo()
> R version 3.2.0 (2015-04-16)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Hmisc_3.17-1      ggplot2_2.0.0     Formula_1.2-1     survival_2.38-3   lattice_0.20-33   mzR_2.4.0  
 [7] rcdk_3.3.2        fingerprint_3.5.2 RMassBank_1.99.9  Rcpp_0.12.3

**Comment by ermueller** [comment]
Was a rather rare occurrence that apparently has never happened before, huh.
The fix is in b54985373dc94cce8d80d25e45404c524a49b58d :)

Please note: 8 of the compounds have this problem:
1: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary",  :
  The spectra count of the substance 8052 (2 spectra) doesn't match the provided spectra list (1 spectra).
2: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary",  :
  The spectra count of the substance 8076 (2 spectra) doesn't match the provided spectra list (1 spectra).
3: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary",  :
  The spectra count of the substance 8077 (2 spectra) doesn't match the provided spectra list (1 spectra).
4: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary",  :
  The spectra count of the substance 8079 (2 spectra) doesn't match the provided spectra list (1 spectra).
5: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "recalibrated",  :
  The spectra count of the substance 8052 (2 spectra) doesn't match the provided spectra list (1 spectra).
6: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "recalibrated",  :
  The spectra count of the substance 8076 (2 spectra) doesn't match the provided spectra list (1 spectra).
7: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "recalibrated",  :
  The spectra count of the substance 8077 (2 spectra) doesn't match the provided spectra list (1 spectra).
8: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "recalibrated",  :
  The spectra count of the substance 8079 (2 spectra) doesn't match the provided spectra list (1 spectra).

Is this meant to be this way? The second spectrum that is in those files gets dropped with the current settings and I'm 99.9% certain that the mzR retrieval works.

**Comment by schymane** [comment]
what was the reason? It wasn't the 2 spectra not 1, right?
I will check the raw files, Martin did 4 scans data-dependent after each MS1 with inclusion list and in the raw files I looked at no masses were repeated so I only tried to extract one, or I'd have got a warning the other way.
Maybe if there aren't many masses on the list (some were only small runs) they are repeated. Can let you know. 
Thanks for the quick fix :) Is that in your repo then?

**Comment by ermueller** [comment]
> what was the reason? It wasn't the 2 spectra not 1, right?

No, it was a data.frame where a column hasn't been added because of several unlucky circumstances. (And this was the one combination nobody thought of) 

But on the other hand, maybe this is just a problem which relates to the R version since there were quite a few behavioural changes in 3.3. I honestly don't know, but it works now.

Took me a while to find out what goes wrong where.

**Comment by schymane** [comment]
I'm still using R3.2.0 - but whatever the cause, the fix worked :-)
No problems getting through the whole dataset but an additional few substances with 2 spectra...
But this in itself is an interesting phenomenon: the acquisition was data dependent, 4 MS2 scans after each MS1 and once one mass is triggered, it's usually excluded. So here's what happened:
For 8052 there are two scans, 197.10 and 197.01. The MS2 are effectively identical, the precursor found is 197.10 and the HCD is 35 for both.
For 8076 there is a 119.06 and a 119.11; again both spectra almost identical for precursor 119.06.
For 8077: 136.08 and 136.11 at RT=3.77; for 8079 there's 136.08 and 136.11 at RT=0.77. I guess for the others this will be the same.
So this is an issue of too many masses that are too close on the inclusion list? But in end effect it doesn't matter because as long as those substances have different retention times, the spectra (in this case) will be identical because only one of the two substances is present at one time. RMB will take the first which would be the best anyway.
What is our "error margin" on the precursor selection? This is mzCoarse: 0.5, right?
