### ISSUE TITLE
Dealing with formulas/SMILES containing non-standard elements

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#158]
> loadList(cmpd_list)
> Error in value[[3L]](cond) : 
>   'Formula' value for compound 8000 in line 1 of the compound list is not a valid Formula

Formula=C2H2DN3
Works fine if Level=5 (unknown) when RMB takes the mz instead of the formula.
So - is this specific to D, or is this any non-standard element? Or should it be [2H] or something?

To take this further, is this specific to loadList? Can we even process formulas (or even SMILES) with non-standard elements, or is our current functionality recognising the isotopes of "normal" substances?
Ideas?

**Comment by ermueller** [comment]
It *technically* works with smiles:
````
> MOL1 <- parse.smiles("C")[[1]]
> MOL2 <- parse.smiles("C[2H]")[[1]]
> do.aromaticity(MOL1)
[1] FALSE
> do.typing(MOL1)
> do.isotopes(MOL1)
> do.aromaticity(MOL2)
[1] FALSE
> do.typing(MOL2)
> do.isotopes(MOL2)
> get.exact.mass(MOL1)
[1] 16.0313
> get.exact.mass(MOL2)
[1] 17.03758
````

but we're not using "get.exact.mass" because we convert everything to cdkFormula since we need that for the annotation.

````
> get.mol2formula(MOL1)
cdkFormula:  CH4 , mass =  16.0313 , charge =  0 
> get.mol2formula(MOL2)
cdkFormula:  CH4 , mass =  16.0313 , charge =  0
````

And cdkFormula class can technically hold isotopic information, but I think this was meant to be implemented in the future, because it currently doesn't get used (afaik?):

````
> FOR1 <- get.mol2formula(MOL1)
> FOR2 <- get.mol2formula(MOL2)
> FOR1@isotopes
     isoto number mass         
[1,] "C"   "1"    "12"         
[2,] "H"   "4"    "1.007825032"
> FOR2@isotopes
     isoto number mass         
[1,] "C"   "1"    "12"         
[2,] "H"   "4"    "1.007825032"
````

So I tried my hand at using Java because the Java object is still inside of the cdkFormula-class and therefore FOR1 and FOR2:

````
> manipulator <- .jnew("org/openscience/cdk/tools/manipulator/MolecularFormulaManipulator")
> MASS <- .jcall(manipulator,
+                            "D",
+                            "getTotalExactMass",
+                            FOR1@objectJ)
> MASS2 <- .jcall(manipulator,
+                 "D",
+                 "getTotalExactMass",
+                 FOR2@objectJ)
> MASS
[1] 16.0313
> MASS2
[1] 16.0313
````

And it isn't different anymore :(

I looked at the code in cdk, https://github.com/rajarshi/cdkr/blob/master/rcdk/R/formula.R and I noticed that isotope info sadly gets lost in conversion, because the formula string from the IAtomContainer is used to convert it to this class, and not the Molecule itself. There is very probably a good reason for that, maybe there were problems with some fringe cases.

It's definitely possible if we use cdk java classes ourselves, but even then "generate.formula" does not have isotopes in its scope, so we'd need to do that, too. This should be possible using the [MolecularFormulaGenerator class](http://cdk.github.io/cdk/1.5/docs/api/org/openscience/cdk/formula/MolecularFormulaGenerator.html). 

All of this is possible using Java cdk, is what I'm trying to say.

One positive side effect of doing all this would be that we wouldn't need my isotopic annotation function any more because that stuff could be done automatically with a new "generate.formula".

**Comment by schymane** [comment]
I think this has been solved with upgrades to CDK ... my recent problems with non-standard elements came from our internal code not dealing with them, not the CDK. CDK2.0 now deals with isotopes etc well. Closing for now.
