### ISSUE TITLE
AAA in global environment

### ISSUE THREAD

**Issue by meowcat** [MassBank/RMassBank#160]
Hi @ermueller,
in https://github.com/MassBank/RMassBank/blob/master/R/createMassBank.R#L1691
`.GlobalEnv$AAA <- mbrecord`

Do you still need this or can I remove it? Otherwise can we try to find a better solution?

**Comment by ermueller** [comment]
Whoops, that was a debug variable since recover only returned gibberish concerning a bug. Yes, you can remove that.

**Comment by uchem-massbank** [comment]
Ah I was wondering where this AAA came from! :-)

**Comment by meowcat** [comment]
Another question, in zzz.R we have utils::globalVariables(c("cpdID", "isotopes","mzCalc"))

Is this needed / where is it used?

**Comment by ermueller** [comment]
There is a weird quirk where NOTEs saying "seems like this doesn't exist" will turn up in R CMD check when a variable has been altered by anything but certain kinds of assignment. 

The variables are pseudo-set globally so that the NOTEs don't turn up in the R CMD check anymore. Just cosmetic, but it's the officially sanctioned solution to that problem.

**Comment by ermueller** [comment]
This has been fixed, I just checked by grepping the main and the s4power branches
