### ISSUE TITLE
Get feedback why spectra/peaks are gone

### ISSUE THREAD

**Issue by Treutler** [MassBank/RMassBank#186]
When I started using RMassBank, my biggest problem was to find out why spectra/peaks are not exported to MassBank records. There are many reasons such as (i) the precursor ion of some compound is completely missing in the data, (ii) the precursor ion is outside of the rt-window, (iii) the mass error is larger then the specified PPM, multiplicityFilter, ppmFine, specOkLimit, and probably many more.

I think it would really help if there would be (optional) output which states for each workflow step which data was not found / was filtered. I would implement an optional parameter 'verbose' in the 'RMassBank.env' and add some output to the corresponding functions.

**Comment by meowcat** [comment]
Looking at the output of `getData(RmbSpectrum2)` should list you everything that was calculated - it does not specifically tell you why a peak is out, but you can usually see. I would welcome if people tried `s4power` branch, since this allows for the addition of arbitrary additional attributes (internally stored as columns of a data frame) to `RmbSpectrum2` objects.
