### ISSUE TITLE
Add DTXSIDs into RMassBank identifiers

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#215]
The EPA have preliminary webservices now available to retrieve DTXSIDs by InChIKey, we should add this into RMassBank to retrieve these for new records (and note that this may change again in the future)

https://github.com/MassBank/RMassBank/blob/master/R/webAccess.R

https://actorws.epa.gov/actorws/chemIdentifier/v01/resolve?identifier=IKHGUXGNUITLKF-UHFFFAOYSA-N 
https://actorws.epa.gov/actorws/chemIdentifier/v01/resolve.json?identifier=IKHGUXGNUITLKF-UHFFFAOYSA-N 
https://actorws.epa.gov/actorws/chemIdentifier/v01/resolve.xml?identifier=IKHGUXGNUITLKF-UHFFFAOYSA-N 

@adelenelai would you be interested in looking into this?

We are looking at doing this initially database side to get DTXSIDs into records already created: 
https://github.com/MassBank/MassBank-data/issues/66
and
https://github.com/MassBank/MassBank-web/issues/80

**Comment by adelenelai** [comment]
working on it

**Comment by meier-rene** [comment]
We have added this in MassBank. If you like you can skip this because its easy to post process records in MassBank.

**Comment by tsufz** [comment]
@meier-rene I don't agree to progress everything with MassBank only. MassBank records should be applicable on a private repository with parsing tools without MassBank in game. DTXSID is an important identifier and thus it should be processed with RMassBank.

**Comment by adelenelai** [comment]
Hi, EPA webservices seem to be down now, the links in @schymane 's original post don't work @ChemConnector 
Are there new URLs which work?

**Comment by ChemConnector** [comment]
The services are down because they ran an update overnight and one of the
certificates expired and broke things. They are working on it in production
(NOT our team) and hopefully things will come up soon. Apologies for the
inconvenience.

Tony Williams

Phone: +1 (919) 201-1516
Email: tony27587@gmail.com
Skype: tony27587
My Blog: www.chemconnector.com
Twitter: http://twitter.com/ChemConnector

**Comment by schymane** [comment]
The services should be up again @adelenelai can you check if they work for you now?
See also https://github.com/MassBank/MassBank-data/issues/68 for updates

**Comment by adelenelai** [comment]
Note (mostly to self, also for documentation):

It is possible for a DTXSID to not exist for a particular compound, because not all stereochemistries of a compound exist in the CompTox Dashboard. 

Assuming webservices and Dashboard are in sync, (see MassBank/MassBank-data#68) any attempts to manually curate infolists in Step 2 of mbWorkflow for DTXSID will not be successful either - the DTXSID just does not exist!

Therefore, if final MB record does not contain the field `CH$LINK: COMPTOX`, it should not be perceived as bug but rather reflects inherent non-existence of that particular DTXSID. (This behaviour was modelled after that of other pre-existing identifiers e.g. CHEBI.)

Whether an explicit declaration should be incorporated for these cases e.g. `CH$LINK: COMPTOX **none found**` is another issue...

In future: if the DTXSID does come into existence over time, post-MB-record-generation-and-upload, Rene's post-processing would be handy.

**Comment by schymane** [comment]
Yes, it is common that identifiers are missing, so modelling this on the way that ChEBI identifiers are handled is the right way to go ... I don't think we need an explicit declaration because the fact that it is missing is implicitly clear in the absence of a corresponding entry in the infolist. Some of the identifiers like KEGG, ChEBI and LipidMaps have very few matches and explicit statements would get annoying over time... and yes, Rene's workflow will catch those that do appear later. 
The validation should account for potential identifier deprecation over time ... but this is another (trickier) topic ... @meier-rene
