### ISSUE TITLE
Three letter Prefix for MB records

### ISSUE THREAD

**Issue by michaelwitting** [MassBank/RMassBank#226]
Hi,
maybe I didn't find it, but is there already a support for three letter prefixes in RMassBank?
We change our prefixes at the BGC to differentiate between the same measurements on three different Q-ToFs (Bruker, Agilent, Sciex)
Best,
Michael

**Comment by meowcat** [comment]
Undocumented and buggy:

https://github.com/MassBank/RMassBank/blob/17c69e1cc69ef80d18fc0e45f02a3a2ff43549b6/R/buildRecord.R#L351-L356

@pstahlhofen: 
* fix the `ACCESSSION` typo
* change it such that `accessionBuilder` takes `cpd, spectrum, subscan` because this gives the user much more freedom
* If you feel fancy, you can try to make the built-in `.getAccession` work directly on the collision energies from `getOption("RMassBank")$spectraList` so that `subscan`

@michaelwitting @tsufz
As you see, you can make your records have any accession number you want:
* add `accessionBuilder: myfunction` to the settings file
* define a `myfunction <- function(cpd, subscan)` or soon `cpd, spectrum, subscan` which returns an accession number for the spectrum

Also to do: document this behaviour

**Comment by sneumann** [comment]
Hi, 
one thing I stumbled across recently is that the regular expression(s) 
for MassBank accessions to already appear in some places, e.g. @schymane and @egonw 
got MassBank added to Wikidata, including the definition for the accession. 
See https://www.wikidata.org/wiki/Property:P6689 `format as a regular expression`,
which defines two or three letters, but not Arbitrary number.
Other definitions are in https://registry.identifiers.org/registry/massbank 
also specifying 2-3 letter prefixes. 

Yours, 
Steffen

**Comment by tsufz** [comment]
Hi,
I agree with Steffen. This was not my intention. My intention was to get a more flexible generation of the number part of the Accession building, but not to scrutinise the format itself.

Best,
Tobias

**Comment by pstahlhofen** [comment]
Three letter prefixes for internal use are now allowed since 87617ed731b32d18c1e376280bf9c820e9ccfce6 so I'll close this
