### ISSUE TITLE
Merge and upstream S4Power branch 

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#227]
Hi, I think it is important to merge the S4power branch as soon as possible. 
Currently it is slightly hidden in a branch, but needs more testing and at the same time 
it fixes several irks people have, and is mentioned in e.g.  #224 #219 #186 #171 #153 #143 #138 #42.
I heard several people (including me) saying they don't use it 
because they use stock BioC installs of RMB. It should not be merged too close 
to the next BioC release, to get some ironing out. Yours, Steffen

**Comment by meowcat** [comment]
Hi,
yes, I fully support this; the reason this hasn't been done is because I haven't been able to keep track with the updates in the base(master) branch and there might be things fixed in the current version that I haven't fixed in s4power. It would be great if we could agree on a path forward! Dagstuhl too late?

**Comment by sneumann** [comment]
Hi, have you seen https://github.com/MassBank/RMassBank/pull/231 
which tries to pull some of the changes into `master` ? Unfortunately there are 
several more merge conflicts, so the rest needs more manual intervention. Yours, Steffen

**Comment by meowcat** [comment]
s4 is merged. Push to Bioc awaiting
