### ISSUE TITLE
Extend RMassBank to deal with isotopes in MS/MS

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#58]
_Issue by **[schymane](https://github.com/schymane)** from Wednesday Jan 15, 2014 at 13:04 GMT_
_Originally opened as https://github.com/sneumann/RMassBank/issues/50_

---

e.g. using enviPat?
Would require data with isolation width > 1.5 Da (=> IPB?).
Longer term issue, other issues should be addressed first, in my opinion.

**Comment by ermueller** [comment]
Just for the record, I'm still kind of unhappy with how my [current solution](https://github.com/ermueller/RMassBank/blob/master/R/Isotopic_Annotation.R) handles this. It works 90% of the time, but some isotope peaks seem "obvious" but get thrown out or not even detected in the first place for some reason or another. I also want to remove all the arguments to that function, since you could reasonably automate it.

**Comment by meowcat** [comment]
@tsufz @schymane If I am not mistaken, this is in the current version. Is this in use? Does this need a change?

**Comment by schymane** [comment]
Athens are submitting with isotope annotation ... I think we can close this ... and reopen a new issue if issues are encountered.
